SELECT r.r_id, r.f_id, r.seat_num, r.r_date, p.p_name, p.p_email
FROM reservation r
INNER JOIN passenger p
ON r.p_id = p.p_id;
# to get  reservation details along with the passenger name and email etc

SELECT p.p_name, r.r_id, r.r_date, r.f_id
FROM passenger p
INNER JOIN reservation r ON r.p_id = p.p_id
WHERE r.r_date = (
  SELECT MAX(r2.r_date)
  FROM reservation r2
  WHERE r2.p_id = p.p_id
);
# find the latest reservation date for each passenger

SELECT p.p_name, r.r_id, r.r_date, r.f_id
FROM passenger p
INNER JOIN (
  SELECT p_id, MAX(r_date) AS latest_r_date
  FROM reservation
  GROUP BY p_id
) latest_res ON r.p_id = latest_res.p_id AND r.r_date = latest_res.latest_r_date;


SELECT r.r_id, p.p_name, f.origin, f.destination, f.f_date, f.dep_time, f.arrival_time
FROM reservation r
INNER JOIN passenger p ON r.p_id = p.p_id
INNER JOIN flight f ON r.f_id = f.f_id;
# Select all reservations with passenger and flight details

SELECT p.p_name, COUNT(r.r_id) as num_reservations
FROM passenger p
LEFT JOIN reservation r ON r.p_id = p.p_id
GROUP BY p.p_id;
# Select all passengers with their total number of reservations

SELECT f.f_id, f.origin, f.destination
FROM flight f
WHERE f.f_id NOT IN (SELECT r.f_id FROM reservation r);
# Select all flights that have no reservations

SELECT p.p_name, p.age, p.p_email
FROM passenger p
INNER JOIN reservation r ON r.p_id = p.p_id
INNER JOIN flight f ON r.f_id = f.f_id
WHERE f.destination = 'Delhi';
# Select all passengers who have flown to a specific destination

SELECT r.f_id, COUNT(r.r_id) as num_reservations
FROM reservation r
GROUP BY r.f_id;
# Find the total number of reservations for each flight

SELECT r.f_id, AVG(p.age) as avg_age
FROM reservation r
INNER JOIN passenger p ON r.p_id = p.p_id
GROUP BY r.f_id;
# Find the average age of passengers for each flight

SELECT r.f_id, SUM(f.prices) as total_revenue
FROM reservation r
INNER JOIN flight f ON r.f_id = f.f_id
GROUP BY r.f_id;
# Find the total revenue generated by each flight

SELECT * FROM reservation WHERE p_id = 1234;
# Retrieving all reservations for a specific passenger

SELECT f_id, COUNT(*) as total_reservations FROM reservation GROUP BY f_id;
# Retrieving the total number of reservations by flight

UPDATE reservation SET seat_num = 12 WHERE r_id = 5678;
# Updating the seat number for a specific reservation

INSERT INTO flight (f_id, origin, destination, f_date, dep_time, arrival_time, prices) VALUES (22222, 'Delhi', 'Mumbai', '2023-05-01', '12:00:00', '14:00:00', 3000);
# Inserting a new flight into the flight table

DELETE FROM payment WHERE pay_id = 789;
# Deleting a payment from the payment table

SELECT f.f_id, f.origin, f.destination, f.f_date, f.dep_time, f.arrival_time, f.prices
FROM flight f
LEFT JOIN reservation r ON f.f_id = r.f_id
WHERE f.f_date = '2023-05-01' AND (r.seat_num IS NULL OR r.seat_num < 50);
# Retrieving all flights with available seats on a specific date

SELECT *
FROM passenger
WHERE p_id NOT IN (SELECT DISTINCT p_id FROM payment);
# Find the passengers who have not made any payments

SELECT p.p_id, p.p_name
FROM passenger p
WHERE p.p_id IN (
    SELECT p_id
    FROM ticket
    GROUP BY p_id
    HAVING COUNT(DISTINCT f_id) > 1
);
# passengers who have flown on more than one flight

SELECT f.f_id, f.f_date, COUNT(*) AS num_trips
FROM flight f
JOIN reservation r ON f.f_id = r.f_id
GROUP BY f.f_id, f.f_date
HAVING COUNT(*) > 1;
# nd flights that have traveled more than once on the same date
